### PR TITLE
Fix disabled optgroups not being disabled in dropkick

### LINKED ISSUE #336: Disabled optgroup not detected
### Version of Dropkick:

2.1.8
### Expected Behavior

Optgroup items and it's label should be marked disabled.
### Actual Behavior

Both work as if they were not disabled. There are also no classes about it added to the markup.
### JSBin / Example repo / Failing test:

Here is a codepen template for reproducing bugs: http://codepen.io/LostKobrakai/pen/XKdbEK

### PR DESCRIPTION
**Pull request by Robdel12**
Fixes #336

### CODE REVIEW

File: src/dropkick.js [hunk 1]
```diff
@@ -1103,6 +1103,7 @@ Dropkick.build = function( sel, idpre ) {
         case "OPTGROUP":
           optgroup = _.create( "li", { "class": "dk-optgroup" });
 
+
```
Comment (wwilsman) [inline src/dropkick.js]: Who doesn't check their diffs before a commit? 😜

Comment (Robdel12) [inline src/dropkick.js]: This guy
